openapi: 3.0.0
info:
  version: 2-oas3
  title: KvK.GsaSearch.WebApi
paths:
  /api/v2/search/companies:
    get:
      tags:
        - Companies
      summary: Get a list with basic information about companies
      operationId: Companies_GetCompaniesBasicV2
      parameters:
        - name: kvkNumber
          in: query
          description: >-
            KvK number, identifying number for a registration in the Netherlands
            Business Register. Consists of 8 digits
          required: false
          schema:
            type: string
        - name: branchNumber
          in: query
          description: >-
            Branch number (Vestigingsnummer), identifying number of a branch.
            Consists of 12 digits
          required: false
          schema:
            type: string
        - name: rsin
          in: query
          description: >-
            RSIN is an identification number for legal entities and
            partnerships. Consist of only digits
          required: false
          schema:
            type: string
        - name: street
          in: query
          description: Street of an address
          required: false
          schema:
            type: string
        - name: houseNumber
          in: query
          description: House number of an address
          required: false
          schema:
            type: string
        - name: postalCode
          in: query
          description: 'Postal code or ZIP code, example 1000AA'
          required: false
          schema:
            type: string
        - name: city
          in: query
          description: City or Town name
          required: false
          schema:
            type: string
        - name: tradeName
          in: query
          description: The name under which a company or a branch of a company operates;
          required: false
          schema:
            type: string
        - name: includeFormerTradeNames
          in: query
          description: >-
            Indication (true/false) to search through expired trade names and
            expired registered names and/or include these in the results.
            Default is false
          required: false
          schema:
            type: boolean
        - name: includeInactiveRegistrations
          in: query
          description: "Indication (true/false) to include searching through inactive dossiers/deregistered companies. Default is false.\r\nNote: History of inactive companies is after 1 January 2013"
          required: false
          schema:
            type: boolean
        - name: mainBranch
          in: query
          description: Search includes main branches. Default is true
          required: false
          schema:
            type: boolean
        - name: branch
          in: query
          description: Search includes branches. Default is true
          required: false
          schema:
            type: boolean
        - name: legalPerson
          in: query
          description: Search includes legal persons. Default is true
          required: false
          schema:
            type: boolean
        - name: startPage
          in: query
          description: >-
            Number indicating which page to fetch for pagination. Default = 1,
            showing the first 10 results
          required: false
          schema:
            type: string
        - name: site
          in: query
          description: Defines the search collection for the query
          required: false
          schema:
            type: string
        - name: context
          in: query
          description: User can optionally add a context to identify his result later on
          required: false
          schema:
            type: string
        - name: q
          in: query
          description: Free format text search for in the compiled search description.
          required: false
          schema:
            type: string
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
            text/html:
              schema:
                $ref: '#/components/schemas/SearchResult'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
               type: string
               example: Bad Request
            text/json:
              schema:
               type: string
               example: Bad Request
            text/html:
              schema:
               type: string
               example: Bad Request
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
               type: string
               example: Forbidden
            text/json:
              schema:
               type: string
               example: Forbidden
            text/html:
              schema:
               type: string
               example: Forbidden
  /api/v2/testsearch/companies:
    get:
      tags:
        - CompaniesTest
      summary: Get a list with basic information about companies
      operationId: CompaniesTest_GetCompaniesBasicV2
      parameters:
        - name: kvkNumber
          in: query
          description: >-
            KvK number, identifying number for a registration in the Netherlands
            Business Register. Consists of 8 digits
          required: false
          schema:
            type: string
        - name: branchNumber
          in: query
          description: >-
            Branch number (Vestigingsnummer), identifying number of a branch.
            Consists of 12 digits
          required: false
          schema:
            type: string
        - name: rsin
          in: query
          description: >-
            RSIN is an identification number for legal entities and
            partnerships. Consist of only digits
          required: false
          schema:
            type: string
        - name: street
          in: query
          description: Street of an address
          required: false
          schema:
            type: string
        - name: houseNumber
          in: query
          description: House number of an address
          required: false
          schema:
            type: string
        - name: postalCode
          in: query
          description: 'Postal code or ZIP code, example 1000AA'
          required: false
          schema:
            type: string
        - name: city
          in: query
          description: City or Town name
          required: false
          schema:
            type: string
        - name: tradeName
          in: query
          description: The name under which a company or a branch of a company operates;
          required: false
          schema:
            type: string
        - name: includeFormerTradeNames
          in: query
          description: >-
            Indication (true/false) to search through expired trade names and
            expired registered names and/or include these in the results.
            Default is false
          required: false
          schema:
            type: boolean
        - name: includeInactiveRegistrations
          in: query
          description: "Indication (true/false) to include searching through inactive dossiers/deregistered companies. Default is false.\r\nNote: History of inactive companies is after 1 January 2013"
          required: false
          schema:
            type: boolean
        - name: mainBranch
          in: query
          description: Search includes main branches. Default is true
          required: false
          schema:
            type: boolean
        - name: branch
          in: query
          description: Search includes branches. Default is true
          required: false
          schema:
            type: boolean
        - name: legalPerson
          in: query
          description: Search includes legal persons. Default is true
          required: false
          schema:
            type: boolean
        - name: startPage
          in: query
          description: >-
            Number indicating which page to fetch for pagination. Default = 1,
            showing the first 10 results
          required: false
          schema:
            type: string
        - name: site
          in: query
          description: Defines the search collection for the query
          required: false
          schema:
            type: string
        - name: context
          in: query
          description: User can optionally add a context to identify his result later on
          required: false
          schema:
            type: string
        - name: q
          in: query
          description: Free format text search for in the compiled search description.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
            text/html:
              schema:
                $ref: '#/components/schemas/SearchResult'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
               type: string
               example: Bad Request
            text/json:
              schema:
               type: string
               example: Bad Request
            text/html:
              schema:
               type: string
               example: Bad Request
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
               type: string
               example: Forbidden
            text/json:
              schema:
               type: string
               example: Forbidden
            text/html:
              schema:
               type: string
               example: Forbidden
servers:
  - url: 'https://api.kvk.nl/'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  schemas:
    SearchResult:
      type: object
      properties:
        apiVersion:
          type: string
          example: "2.0"
        meta:
          type: object
        data:
          type: object
          $ref: "#/components/schemas/ResultData_CompanyBasicV2"
    CompanyBasicV2:
      type: object
      properties:
        kvkNumber:
          type: string
        branchNumber:
          type: string
        rsin:
          type: string
        tradeNames:
          $ref: '#/components/schemas/CompanySearchV2TradeNames'
        hasEntryInBusinessRegister:
          type: boolean
        hasNonMailingIndication:
          type: boolean
        isLegalPerson:
          type: boolean
        isBranch:
          type: boolean
        isMainBranch:
          type: boolean
        addresses:
          description: At most 1 address is returned
          type: array
          items:
            $ref: '#/components/schemas/CompanySearchV2Address'
        websites:
          type: array
          items:
            type: string
    CompanySearchV2TradeNames:
      type: object
      properties:
        businessName:
          type: string
        shortBusinessName:
          type: string
        currentTradeNames:
          type: array
          items:
            type: string
        formerTradeNames:
          type: array
          items:
            type: string
        currentStatutoryNames:
          type: array
          items:
            type: string
        formerStatutoryNames:
          type: array
          items:
            type: string
        currentNames:
          type: array
          items:
            type: string
        formerNames:
          type: array
          items:
            type: string
    CompanySearchV2Address:
      type: object
      properties:
        type:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        houseNumberAddition:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
    ResultData_CompanyBasicV2:
      description: Standardized Resultdata
      type: object
      properties:
        itemsPerPage:
          format: int32
          description: Amount of search results per page used for the query
          type: integer
        startPage:
          format: int32
          description: The current page of the results
          type: integer
        totalItems:
          format: int32
          description: Total amount of results spread over multiple pages
          type: integer
        nextLink:
          description: Link to next set of ItemsPerPage result items
          type: string
        previousLink:
          description: Link to previous set of ItemsPerPage result items
          type: string
        items:
          description: Actual search results
          type: array
          items:
            $ref: '#/components/schemas/CompanyBasicV2'