openapi: 3.0.0
info:
  version: 2-oas3
  title: KvK.GsaSearch.WebApi
paths:
  /api/v2/profile/companies:
    get:
      tags:
        - Companies
      summary: Get extended information about a specific company or establishment
      operationId: Companies_GetCompaniesExtendedV2
      parameters:
        - name: kvkNumber
          in: query
          description: >-
            KvK number, identifying number for a registration in the Netherlands
            Business Register. Consists of 8 digits
          required: false
          schema:
            type: string
        - name: branchNumber
          in: query
          description: >-
            Branche number (Vestigingsnummer), identifying number of a branch.
            Consists of 12 digits
          required: false
          schema:
            type: string
        - name: rsin
          in: query
          description: >-
            RSIN is an identification number for legal entities and
            partnerships. Consist of only digits
          required: false
          schema:
            type: string
        - name: includeInactiveRegistrations
          in: query
          description: "Indication (true/false) to include searching through inactive dossiers/deregistered companies. Default is false.\r\nNote: History of inactive companies is after 1 January 2013"
          required: false
          schema:
            type: boolean
        - name: restrictToMainBranch
          in: query
          description: Search is restricted to main branches. Default is false.
          required: false
          schema:
            type: boolean
        - name: site
          in: query
          description: Defines the search collection for the query
          required: false
          schema:
            type: string
        - name: context
          in: query
          description: User can optionally add a context to identify his result later on
          required: false
          schema:
            type: string
        - name: q
          in: query
          description: Free format text search for in the compiled search description.
          required: false
          schema:
            type: string
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ProfileResult'
            text/html:
              schema:
                $ref: '#/components/schemas/ProfileResult'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
               type: string
               example: Bad Request
            text/json:
              schema:
               type: string
               example: Bad Request
            text/html:
              schema:
               type: string
               example: Bad Request
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
               type: string
               example: Forbidden
            text/json:
              schema:
               type: string
               example: Forbidden
            text/html:
              schema:
               type: string
               example: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
            text/json:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
            text/html:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
  /api/v2/testprofile/companies:
    get:
      tags:
        - CompaniesTest
      summary: Get extended information about a specific company or establishment
      operationId: CompaniesTest_GetCompaniesExtendedV2
      parameters:
        - name: kvkNumber
          in: query
          description: >-
            KvK number, identifying number for a registration in the Netherlands
            Business Register. Consists of 8 digits
          required: false
          schema:
            type: string
        - name: branchNumber
          in: query
          description: >-
            Branche number (Vestigingsnummer), identifying number of a branch.
            Consists of 12 digits
          required: false
          schema:
            type: string
        - name: rsin
          in: query
          description: >-
            RSIN is an identification number for legal entities and
            partnerships. Consist of only digits
          required: false
          schema:
            type: string
        - name: includeInactiveRegistrations
          in: query
          description: "Indication (true/false) to include searching through inactive dossiers/deregistered companies. Default is false.\r\nNote: History of inactive companies is after 1 January 2013"
          required: false
          schema:
            type: boolean
        - name: restrictToMainBranch
          in: query
          description: Search is restricted to main branches. Default is false.
          required: false
          schema:
            type: boolean
        - name: site
          in: query
          description: Defines the search collection for the query
          required: false
          schema:
            type: string
        - name: context
          in: query
          description: User can optionally add a context to identify his result later on
          required: false
          schema:
            type: string
        - name: q
          in: query
          description: Free format text search for in the compiled search description.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ProfileResult'
            text/html:
              schema:
                $ref: '#/components/schemas/ProfileResult'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
               type: string
               example: Bad Request
            text/json:
              schema:
               type: string
               example: Bad Request
            text/html:
              schema:
               type: string
               example: Bad Request
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
               type: string
               example: Forbidden
            text/json:
              schema:
               type: string
               example: Forbidden
            text/html:
              schema:
               type: string
               example: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
            text/json:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
            text/html:
              schema:
                $ref: "#/components/schemas/ResultData_ErrorResult404"
servers:
  - url: 'https://api.kvk.nl/'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  schemas:
    ProfileResult:
      type: object
      properties:
        apiVersion:
          type: string
          example: "2.0"
        meta:
          type: object
        data:
          type: object
          $ref: "#/components/schemas/ResultData_CompanyExtendedV2"
    CompanyExtendedV2:
      type: object
      properties:
        kvkNumber:
          type: string
        branchNumber:
          type: string
        rsin:
          type: string
        tradeNames:
          $ref: '#/components/schemas/CompanyProfileV2TradeNames'
        legalForm:
          type: string
        businessActivities:
          type: array
          items:
            $ref: '#/components/schemas/CompanyProfileV2BusinessActivity'
        hasEntryInBusinessRegister:
          type: boolean
        hasCommercialActivities:
          type: boolean
        hasNonMailingIndication:
          type: boolean
        isLegalPerson:
          type: boolean
        isBranch:
          type: boolean
        isMainBranch:
          type: boolean
        employees:
          format: int32
          type: integer
        foundationDate:
          type: string
        registrationDate:
          type: string
        deregistrationDate:
          type: string
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/CompanyProfileV2Address'
        websites:
          type: array
          items:
            type: string
    CompanyProfileV2TradeNames:
      type: object
      properties:
        businessName:
          type: string
        shortBusinessName:
          type: string
        currentTradeNames:
          type: array
          items:
            type: string
        formerTradeNames:
          type: array
          items:
            type: string
        currentStatutoryNames:
          type: array
          items:
            type: string
        formerStatutoryNames:
          type: array
          items:
            type: string
        currentNames:
          type: array
          items:
            type: string
        formerNames:
          type: array
          items:
            type: string
    CompanyProfileV2BusinessActivity:
      type: object
      properties:
        sbiCode:
          type: string
        sbiCodeDescription:
          type: string
        isMainSbi:
          type: boolean
    CompanyProfileV2Address:
      type: object
      properties:
        type:
          type: string
        bagId:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        houseNumberAddition:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
        gpsLatitude:
          format: double
          type: number
        gpsLongitude:
          format: double
          type: number
        rijksdriehoekX:
          format: double
          type: number
        rijksdriehoekY:
          format: double
          type: number
        rijksdriehoekZ:
          format: double
          type: number
    ResultData_CompanyExtendedV2:
      description: Standardized Resultdata
      type: object
      properties:
        itemsPerPage:
          format: int32
          description: Amount of search results per page used for the query
          type: integer
        startPage:
          format: int32
          description: The current page of the results
          type: integer
        totalItems:
          format: int32
          description: Total amount of results spread over multiple pages
          type: integer
        nextLink:
          description: Link to next set of ItemsPerPage result items
          type: string
        previousLink:
          description: Link to previous set of ItemsPerPage result items
          type: string
        items:
          description: Actual search results
          type: array
          items:
            $ref: '#/components/schemas/CompanyExtendedV2'
    ResultData_ErrorResult404:
      description: Possible Error Messages
      type: object
      properties:
       code:
        description: http status code
        type: string
        example: 404
       message:
        description: Error Message
        type: string
        example: NotFound
       reason:
        description: Reason for getting the Error Message
        type: string
        example: No companies found for the given query.
      $ref: "#/components/schemas/ResultData_ErrorResult404"