trigger:
- main

pr:
- main

pool:
  name: Default

resources:
  repositories:
    - repository: templates
      type: github
      name: securancy/azure-pipeline-templates
      endpoint: securancy
extends:
  template: dotnet-nuget.yml@templates
  parameters:
    dotNetVersion: '6.0.x'
    feed: 'heartwork'
    environment: 'Production'
